# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala

scala:
  - 2.10.5
  - 2.11.7

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - marco.borst.extern@zalando.de
      - slava.schmidt.extern@zalando.de
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
#  - pip install --user codecov

after_success:
#  - codecov

script:
  - sbt -jvm-opts travis/jvmopts compile test:compile test +publishLocal scripted
