# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala

scala:
  - 2.10.5
  - 2.11.7

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - marco@splatter.nl
      - slavaschmidt@gmx.de
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
#  - pip install --user codecov

after_success:
#  - bash <(curl -s https://codecov.io/bash)

script:
  - sbt -jvm-opts travis/jvmopts compile test +publishLocal
  - sbt -jvm-opts travis/jvmopts scripted
  - sbt -jvm-opts travis/jvmopts < travis_coverage_script.txt


# cache:
#  directories:
#    - $HOME/.ivy2/cache
#    - $HOME/.sbt/boot/

#before_cache:
#  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
#  - find $HOME/.sbt -name "*.lock" -delete
#  - find $HOME/.sbt -name "de.zalando" -delete