# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala

scala:
   - 2.10.5

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - marco.borst.extern@zalando.de
      - slava.schmidt.extern@zalando.de
jdk:
  - oraclejdk8

script:
  - sbt clean coverage test

before_install:
  - pip install --user codecov

after_success:
  - codecov