# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala

scala:
  - 2.10.5
  - 2.11.7

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - marco.borst.extern@zalando.de
      - slava.schmidt.extern@zalando.de
jdk:
  - oraclejdk8

before_install:
  - pip install --user codecov

after_success:
  - codecov

script:
  - sbt compile test:compile test
  #  TODO Disabled because it fails _sometimes_ in travis.
  # +publishLocal scripted
