swagger: '2.0'
info:
  version: 0.0.0
  title: Play Swagger UI
paths:

  /api/{file}:
    get:
      "x-api-first-handler": "SwaggerUIController.static"
      parameters:
        - in: path
          name: path
          required: true
          type: string
      responses:
        200:
          description: OK

  /api/{dir}/{file}:
    get:
      "x-api-first-handler": "SwaggerUIController.static"
      parameters:
        - in: path
          name: path
          required: true
          type: string
        - in: path
          name: dir
          required: true
          type: string
      responses:
        200:
          description: OK

  /api/{dir}/{subdir}/{file}:
    get:
      "x-api-first-handler": "SwaggerUIController.static"
      parameters:
        - in: path
          name: path
          type: string
        - in: path
          name: dir
          type: string
        - in: path
          name: subdir
          type: string
      responses:
        200:
          description: OK
