---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /{username}/{password}:
    post:
      "x-api-first-handler": "admin.Dashboard.index"
      parameters:
        - in: path
          name: username
          description: The name that needs to be deleted
          required: true
          type: string
        - in: path
          default: slava
          name: password
          required: true
          type: string
        - in: query
          name: developer
          type: string
          default: bam
          required: true
      responses:
        200:
          description: OK
